name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정
# main이라는 브랜치에 push 될 때 아래 작업을 실행
on:
  push:
    branches:
      - main

# 하나의 Workflowsms 1개 이상의 Job으로 구성된다.
# 여러 Job은 병렬로 실행된다.
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # Job을 실행하는 환경 / 가장 최신 버전(latest)의 ubuntu를 사용
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"
      - name: 여러 명령어 문장 작성하기
        run: |
          echo "첫 번째 문장"
          echo "두 번째 문장"
          echo "세 번째 문장"
